### ISSUE TITLE
Unpacking floating points value(s) fails on Raspberry PI

### ISSUE THREAD

**Issue by joente** [transceptor-technology/qpack#1]
Reported by @AlmiS

For history on this issue see: https://github.com/transceptor-technology/siridb-server/issues/59

**Comment by Thrasd** [comment]
The unittest is passing now, and I can insert and query data using the siridb-connector. So everything seems to be working!

Thank you for such a quick fix. (I am working on the same project as @AlmiS)

**Comment by joente** [comment]
Thx for testing!
