### ISSUE TITLE
Unsupported types produce corrupted output

### ISSUE THREAD

**Issue by pumelo** [transceptor-technology/qpack#2]
If unsupported types are passed to qpack they are silently ignored and a corrupted output produced.

example to reproduce
```
import qpack, datetime
t = qpack.packb({'d' : datetime.datetime.now()})
qpack.unpackb(t)
```
From my point of view, this should already fail when packing. I suggest to add something like the following to the end of the _pack function to handle the case where an unsupported type is passed to it:

```
    else:
        raise TypeError('%s is not supported for packing with qpack'%(type(obj)))
```
This will raise a TypeError whenever an unsupported type is passed to the function.

**Comment by riklempens** [comment]
@pumelo thanks for reporting this issue, as we are currently in the mids of our vacation season our resources are somewhat limited hence the delayed response. My partner @joente will take this forward next week.

**Comment by joente** [comment]
Fixed by raising a `TypeError` when trying to pack an unsupported type.
Updated both the C lib, the Python fallback and the test.

**Comment by pumelo** [comment]
Awesome , thank you.
